Components/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingApp.WebUI.Repository.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingApp.WebUI.Components
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private ICategoryRepository repository;

        public CategoryMenuViewComponent(ICategoryRepository _repository)
        {
            repository = _repository;
        }

        public IViewComponentResult Invoke()
        {
            return View(repository.GetAllWidthProductCount());
        }

    }
}

Components/FeaturedProductViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingApp.WebUI.Repository.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingApp.WebUI.Components
{
    public class FeaturedProductViewComponent : ViewComponent
    {
        private IProductRepository repository;

        public FeaturedProductViewComponent(IProductRepository _repository)
        {
            repository = _repository;
        }

        public IViewComponentResult Invoke()
        {
            return View(repository.GetAll().Where(i => i.IsApproved && i.IsFeatured).ToList());
        }


    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShoppingApp.WebUI.Entity;
using ShoppingApp.WebUI.Models;
using ShoppingApp.WebUI.Repository.Abstract;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingApp.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public IProductRepository repository;
        public IUnitOfWork uow;

        public HomeController(IProductRepository _repository, IUnitOfWork _uow )
        {
            repository = _repository;
            uow = _uow; 
        }

        public IActionResult Index()
        {
            return View(uow.Products.GetAll().Where(i => i.IsApproved && i.IsHome).ToList());  
            //return View(repository.GetAll());
        }

        public IActionResult Details(int id)
        {
            return View(uow.Products.Get(id));
        }

        public IActionResult Create()
        {
            var prd = new Product()
            {
                ProductName = "Yeni Ürün",
                Price = 1000
            };
            uow.Products.Add(prd);
            uow.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

Views/Home/Index.cshtml
@model IEnumerable<Product>

@{
    ViewData["Title"] = "Home Page";
}
<section id="content">

    <section id="shop" class="container">

        <div class="row">

            <!-- sidebar start -->
            <div id="sidebar" class="col-md-3">

                <div class="widget">
                    <form class="form-inline">
                        <div class="input-group">
                            <input type="text" class="form-control input-lg" placeholder="Search...">
                            <span class="input-group-btn">
                                <button class="btn btn-default btn-lg" type="submit"><i class="fa fa-search"></i></button>
                            </span>
                        </div>

                    </form>
                </div>


                @await Component.InvokeAsync("CategoryMenu") 

                @await Component.InvokeAsync("FeaturedProduct")

            </div>
            <!-- sidebar end -->
            <!-- right column start -->
            <div class="col-md-9">

                <div class="row">

                    <div class="col-md-12 wow fadeIn">
                        <div class="row product-results">
                            <div class="product-results">
                                <div class="col-xs-8">
                                    <p class="woocommerce-result-count">
                                        There are @Model.Count() products
                                    </p>
                                </div>

                            </div>
                        </div>
                    </div>

                    @foreach (var product in Model)
                    { 
                        @Html.Partial("_ProductItem",product)
                    }

                </div>

            </div>
            <!-- right column end -->

        </div>



    </section>

</section>